services:

  wallet-backend:
    container_name: wallet-backend
    build:
      dockerfile: backend.Dockerfile
    env_file: backend.env
    ports:
      - 8286:8086
    command: yarn run start
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://wallet-backend:8086" ]
      interval: 10s
      timeout: 50s
      retries: 3
      start_period: 10s
  #    networks:
  #      - heimdall-network

  wallet-frontend:
    container_name: wallet-frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 19006:19006
      - 8281:8081
    depends_on:
      wallet-backend:
        condition: service_healthy
    command: yarn run web
    tty: true
    #    networks: #TODO make only backend work with the heimdall-network
    #      - heimdall-network
    volumes:
      - ./frontend/src:/app/src
#TODO why CMD in dockerfile has different behaviour?
#
#networks:
#  heimdall-network:
#    external: true